### ISSUE TITLE
uninitialized constant RSpec::Support when running RAILS_ENV=test rake db:migrate

### ISSUE THREAD

**Issue by mosinandrey** [grosser/rspec-instafail#20]
Hello! When I trying to run migration for test environment with rspec-instafail gem I get this exception:

    rake aborted!
    NameError: uninitialized constant RSpec::Support
    /Users/mosin/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.1.7/lib/rspec/core/formatters/progress_formatter.rb:1:in `<top (required)>'
    /Users/mosin/.rvm/gems/ruby-2.2.2/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
    /Users/mosin/.rvm/gems/ruby-2.2.2/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
    /Users/mosin/.rvm/gems/ruby-2.2.2/gems/rspec-instafail-0.2.6/lib/rspec/instafail/rspec_2.rb:1:in `<top (required)>'
    /Users/mosin/.rvm/gems/ruby-2.2.2/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
    /Users/mosin/.rvm/gems/ruby-2.2.2/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
    /Users/mosin/.rvm/gems/ruby-2.2.2/gems/rspec-instafail-0.2.6/lib/rspec/instafail.rb:11:in `<module:RSpec>'
    /Users/mosin/.rvm/gems/ruby-2.2.2/gems/rspec-instafail-0.2.6/lib/rspec/instafail.rb:1:in `<top (required)>'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:85:in `require'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:85:in `rescue in block in require'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:68:in `block in require'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
    /Users/mosin/cater2.me/config/application.rb:5:in `<top (required)>'
    /Users/mosin/cater2.me/Rakefile:5:in `<top (required)>'
    LoadError: cannot load such file -- rspec-instafail
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
    /Users/mosin/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
    /Users/mosin/cater2.me/config/application.rb:5:in `<top (required)>'
    /Users/mosin/cater2.me/Rakefile:5:in `<top (required)>'

If I remove rspec-instafail it runs successfully. What can be the reason?
Thanks!

**Comment by grosser** [comment]
I'm not using it atm, if you find a fix, please post here or even better open a PR :)

**Comment by mosinandrey** [comment]
Ok, will try to investigate it and open a PR if I find the fix. Thanks

**Comment by ketiko** [comment]
@mosinandrey, I found a work around.

Don't require it in your Gemfile.  Then either require it in your .rspec or spec_helper.rb.

``` ruby
# Gemfile
gem 'rspec-instafail', require: false
```

**Comment by mosinandrey** [comment]
@ketiko make sense. Will try it. Thank you :+1:

**Comment by grosser** [comment]
Can you turn that into a PR or a readme change ?
