### ISSUE TITLE
0.3.0 breaks expecting a formatter that isn't present

### ISSUE THREAD

**Issue by hlascelles** [grosser/rspec-instafail#23]
Going from 0.2.6 to 0.3.0 we see the following:

````
lib/ruby/gems/2.1.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- spec/runner/formatter/progress_bar_formatter (LoadError)
	from lib/ruby/gems/2.1.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	from lib/ruby/gems/2.1.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	from lib/ruby/gems/2.1.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from lib/ruby/gems/2.1.0/gems/rspec-instafail-0.3.0/lib/rspec/instafail/rspec_1.rb:1:in `<top (required)>'
````

We're on rspec 2.99.0 if it helps?

**Comment by grosser** [comment]
most likely trying to work with a new rspec version ... are you on rspec 1/2/3 ?

**Comment by hlascelles** [comment]
We're on rspec 2.99.0 if it helps?

**Comment by grosser** [comment]
looks like the `defined?(RSpec::Core)` check fails :(

https://github.com/grosser/rspec-instafail/commit/c449fdc5ec86e2208e8ec7f3a9295babf8b43205

I think I know how to rewrite this ... stay tuned :)

**Comment by grosser** [comment]
plz try 0.4.0 ... if that fails with some require foobar I'll have to put the lib hack back, but I think it should work just fine ...

**Comment by hlascelles** [comment]
Yep, that's done it. Thank you so much!
