### ISSUE TITLE
No output after upgrade to 1.0.0

### ISSUE THREAD

**Issue by wojtha** [grosser/rspec-instafail#28]
No output after upgrade to 1.0.0. Downgrading back to 0.5.0 resolves the issue.

I get the following with version 1.0.0:

```
$ bundle exec rspec spec/models/demo_spec.rb
Run options:
  include {:focus=>true}
  exclude {:slow=>true, :broken=>true}

All examples were filtered out; ignoring {:focus=>true}
```

After downgrading back to 0.5.0 I get expected output:

```
$ bundle exec rspec spec/models/demo_spec.rb
Run options:
  include {:focus=>true}
  exclude {:slow=>true, :broken=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 44819
...........................................

Finished in 1.48 seconds (files took 6.86 seconds to load)
43 examples, 0 failures
```

RSpec 3.4.4
Ruby 2.3.1
Ubuntu 16.04 64bit
ZSH shell with Oh My ZSH plugins

**Comment by grosser** [comment]
updated it to not force dots by default ... add `--format progress # to keep dots appear` ... documented in readme, but hard to know when just doing an update ... not sure how to better communicate that ...

**Comment by wojtha** [comment]
@grosser ok

Maybe you can add `post_install_message` to `gemspec`?

> **post_install_message [RW]**
> A message that gets displayed after the gem is installed.
> Usage:
> `spec.post_install_message = "Thanks for installing!"`

See http://rubygems.rubyforge.org/rubygems-update/Gem/Specification.html

**Comment by wojtha** [comment]
... and maybe some paragraph in Readme could help as well. A paragraph with clear heading like **Instructions for upgrade from 0.5 to 1.0** since the code with comment is really invisible - at least for me. Without your mention I would not see it. When you upgrade such simple gem you usually don't expect that you should reread Readme carefully again...

**Comment by grosser** [comment]
added a comment at the top ... I'm not a fan of post install messages

**Comment by wojtha** [comment]
@grosser nice! thx! :star2:
