### ISSUE TITLE
rspec dependency

### ISSUE THREAD

**Issue by p-decoraid** [grosser/rspec-instafail#30]
Should rspec-instafail depend on rspec-core instead of rspec?

**Comment by grosser** [comment]
Why ?
... Would break rspec 1 support if that still exists ... Otherwise sounds
fine ...

**Comment by p-decoraid** [comment]
... because rspec-instafail is the first gem in my gemfile that pulled in rspec.

I figured it had something to do with compatibility with old rspecs, hence why this is an issue and not a PR.
